-- ============================================================
-- V1: Esquema inicial (restaurantes, usuarios, resenas)
-- PostgreSQL. Debe coincidir con el mapeo JPA para que
-- ddl-auto=validate pase.
-- ============================================================

CREATE TABLE restaurant (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre      VARCHAR(255),
    direccion   VARCHAR(255),
    tipo_comida VARCHAR(255),
    telefono    VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE usuario (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre   VARCHAR(255),
    email    VARCHAR(255),
    password VARCHAR(255),
    PRIMARY KEY (id),
    CONSTRAINT uk_usuario_email UNIQUE (email)
);

CREATE TABLE resena (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    comentario    VARCHAR(255),
    calificacion  DOUBLE PRECISION,
    restaurant_id BIGINT NOT NULL,
    usuario_id    BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_resena_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant (id),
    CONSTRAINT fk_resena_usuario    FOREIGN KEY (usuario_id)    REFERENCES usuario (id)
);

CREATE INDEX idx_resena_restaurant ON resena (restaurant_id);
CREATE INDEX idx_resena_usuario    ON resena (usuario_id);
